### ISSUE TITLE
Plugin can't be found

### ISSUE THREAD

**Issue by skosow** [AMoo-Miki/homebridge-switchmate-ble#1]
npm ERR! 404  'homebridge-switchmate-ble@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by AMoo-Miki** [comment]
I wasn't comfortable publishing this yet. It has been working for me for over a year but devices themselves are sometimes finicky.

I just published it and you can use it. Best of luck.
