### ISSUE TITLE
How to use http section?  Can on/off commands be passed to it via http get?

### ISSUE THREAD

**Issue by famewolf** [AMoo-Miki/homebridge-switchmate-ble#12]
All I get is this:
{"9e10d46c-a1ca-4cc8-9c22-dfb5975bc0e5":"Bedroom Ceiling Fan","b6810eb2-b86e-4785-9020-47079a33ea87":"Kitchen Flourescent Light","a15186d2-49dc-4c9c-a78c-6a2f482ea721:0":"Switchmate Outlet 1 Light","a15186d2-49dc-4c9c-a78c-6a2f482ea721:1":"Switchmate Outlet 1 1","a15186d2-49dc-4c9c-a78c-6a2f482ea721:2":"Switchmate Outlet 1 2"}

and I have no idea what to do with it.  It's not mentioned in the documentation.  Ideally I'd like to be able to pass in http get on and off commands...to for example turn the outlet off when it finishes charging my phone to 100%.

Am I misunderstanding the purpose?

**Comment by AMoo-Miki** [comment]
I just realized that I have to submitted the documentation for it. I will get on it ASAP.

**Comment by AMoo-Miki** [comment]
I made the WebControl a bit easier to use and documented it in the Readme file.
