### ISSUE TITLE
Light Switches turn themselves off

### ISSUE THREAD

**Issue by bwalls** [AMoo-Miki/homebridge-switchmate-ble#4]
I'm was getting a failure when trying to install that says,
"undefined ls-remote -h -t ssh://git@github.com/AMoo-Miki/noble-device.git"

After much work, finally got noble to install on a different system. 

Love the interface and functionality on the plugs! 

However, I'm currently seeing my v3 light switches turning themselves off 5-10 minutes. I went in and deleted the switches from the Switchmate app, but that didn't change the behavior. Any idea what's going on?  One is in the same room as the Raspberry Pi running things, the other is just across the hall. Both are close to working Switchmate plugs.

**Comment by bwalls** [comment]
Here is my configuration. I'm not using the web access, just want HomeKit to work reliably. 

           "platform": "SwitchmateBLE",
            "devices": [
                {
                    "name": "Bryan's Office SM1",
                    "id": "address"
                },
                {
                    "name": " Laundry Room Main Lights SM2",
                    "id": "address"
                },
                {
                    "name": "SM3",
                    "id": "address"
                },
                {
                    "name": "SM4",
                    "id": "address"
                },
                {
                    "name": "SM5",
                    "id": "address"
                },
                {
                    "name": "SM6",
                    "id": "address"
                },
                {
                    "name": "SM12 Outlet",
                    "id": "address"
                },
                {
                    "name": "SM34 Outlet",
                    "id": "address"
                },
                {
                    "name": "SM56 Outlet",
                    "id": "address"
                }
            ]
        }
    ],

**Comment by pingje** [comment]
I am experiencing the same issue. Logs show that the connection is dropped after some time, and when it reconnects, the switch defaults to off.

**Comment by AMoo-Miki** [comment]
I had a similar problem with their new switches. Tried 6 different ones and they all did that. Tried debugging with their support but gave up and returned them.
