### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by bwalls** [AMoo-Miki/homebridge-switchmate-ble#9]
Will the latest version work with Node 12, or does it absolutely need Node 14? Or does upgrading just add something extra? I'm not sure what might break with forcing the update on all of homebridge.

**Comment by vypergts** [comment]
I definitely don't think this new version will work without Node 14. Seems to throw syntax errors on fresh install of hoobs which hasn't updated yet. See post I tried to help troubleshoot here: [https://www.reddit.com/r/HOOBS/comments/jd4nox/help_with_switchmate_ble_plugin/](https://www.reddit.com/r/HOOBS/comments/jd4nox/help_with_switchmate_ble_plugin/)

**Comment by AMoo-Miki** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), certain operators used in the code were only included with NodeJS 14.0.0 and onward. You will need to have at least v14.
